### ISSUE TITLE
disdingwish between TP04 and TP06

### ISSUE THREAD

**Issue by itewk** [etheralm/libpurecool#8]
I just got the TP06 and I see this lib says it doesn't yet support it. though it seems the model number for TP06 and TP04 are the same and in general this library works but probably need a way to distinguish the two models since they have different values. Not having the TP04 I don't know for sure what is different but I know the value for `cflr` (carbon_filter_state) comes back as `INV` which messes up the home-assistant component that uses this library that expects that value to be an INT. While I could just PR against that repo to not assume `carbon_filter_state` will be an INT it would seem we should update this library to have different classes or some flag on the existing `DysonPureCoolV2State` to differentiate the TP04 from the TP06.

I don't know the best way to do this without having raw output from a TP04. I was hoping someone would have that so I could compare the states and see what could be use to differentiate.

Here is the output from TP06

```yaml
[DysonPureCool(
  serial=XXX-XXX-XXXXXXXX,
  active=None,
  name=Master bedroom,
  version=ECG2PF.02.06.002.0001,
  auto_update=True,
  new_version_available=False,
  product_type=438,
  network_device=None)]

{'fpwr': 'ON',
'auto': 'OFF',
'oscs': 'ON',
'oson': 'ON',
'nmod': 'OFF',
'rhtm': 'ON',
'fnst': 'FAN',
'ercd': '11E1',
'wacd': 'NONE',
'nmdv': '0004',
'fnsp': '0001',
'bril': '0002',
'corf': 'OFF',
'cflr': 'INV',
'hflr': '0097',
'cflt': 'SCOF',
'hflt': 'GCOM',
'sltm': 'OFF',
'osal': '0136',
'osau': '0226',
'ancp': 'CUST',
'fdir': 'OFF'}
```
